version: "3"
 
services:
   guacd:
         container_name: guacd
         image: guacamole/guacd
         restart: always
         networks:
            guac-net:
               ipv4_address: 172.30.0.2
   guacweb:
      container_name: guac_web
      image: guacamole/guacamole
      restart: always
      ports:
         - 80:8080
      environment:
         MYSQL_DATABASE: guacamole_db
         MYSQL_HOSTNAME: 172.30.0.3
         MYSQL_PASSWORD: my_passwd
         MYSQL_USER: guacamole_user
         GUACD_HOSTNAME: 172.30.0.2
         GUACAMOLE_CLIENT_CLIPBOARD_DISALLOWED: "true"  # Disables copy-paste
      depends_on:
         - guacamole-sql
         - guacd
      networks:
         guac-net:
 
   guacamole-sql:
      container_name: guac-sql
      image: mysql
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: my_passwd
      volumes:
         - dbdata:/var/lib/mysql
      networks:
         guac-net:
            ipv4_address: 172.30.0.3
volumes:
   dbdata:
networks:
   guac-net:
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: "172.30.0.0/16"
